### PR TITLE
a more polished README.md

### PR DESCRIPTION
**Pull request by TheYahton**
I believe the current README.md lacks clarity.

### CODE REVIEW

**Comment by TheYahton** [comment]
the build commands is incomplete:
```
yahton@YahtonPC:~/projects/rgfw$ gcc test.c -lX11 -lGL -lXrandr
/usr/bin/ld: /tmp/ccltU2tR.o: in function `RGFW_window_checkFPS':
test.c:(.text+0xfb4): undefined reference to `round'
/usr/bin/ld: test.c:(.text+0x11aa): undefined reference to `round'
/usr/bin/ld: /tmp/ccltU2tR.o: in function `RGFW_XCreateMonitor':
test.c:(.text+0x57e9): undefined reference to `round'
/usr/bin/ld: test.c:(.text+0x5819): undefined reference to `round'
/usr/bin/ld: test.c:(.text+0x5a54): undefined reference to `round'
/usr/bin/ld: /tmp/ccltU2tR.o:test.c:(.text+0x5a84): more undefined references to `round' follow
collect2: error: ld returned 1 exit status
```
We definetily should link with math too.

**Comment by ColleagueRiley** [comment]
@TheYahton I think these changes are pretty good. Although I would prefer the example list to be on the homepage, I concede that this is a lot cleaner. 

Thank you for the changes so far.

**Comment by TheYahton** [comment]
> Although I would prefer the example list to be on the homepage

Then maybe leave the screenshot in README.md?
examples

Or add a link to the web examples (https://colleagueriley.github.io/RGFW/)?

**Comment by TheYahton** [comment]
```c
#define RGFW_IMPLEMENTATION
#include "RGFW.h"

void keyfunc(RGFW_window* win, u32 keycode, char keyName[16], u8 lockState, u8 pressed) {
    if (keycode == RGFW_Escape && pressed) {
        RGFW_window_setShouldClose(win);
    }
}

int main() {
    RGFW_window* win = RGFW_createWindow("a window", RGFW_RECT(0, 0, 800, 600), (u64)RGFW_CENTER);

    RGFW_setKeyCallback(keyfunc);
    // if you don't like callbacks you can use RGFW_window_checkEvent in a loop (check the examples).

    while (!RGFW_window_shouldClose(win)) {
        RGFW_window_checkEvents(win, 0);
        
        glClearColor(0.1f, 0.1f, 0.1f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        // You can use modern OpenGL techniques, but this method is more straightforward for drawing just one triangle.
        glBegin(GL_TRIANGLES);
        glColor3f(1, 0, 0); glVertex2f(-0.6, -0.75);
        glColor3f(0, 1, 0); glVertex2f(0.6, -0.75);
        glColor3f(0, 0, 1); glVertex2f(0, 0.75);
        glEnd();

        RGFW_window_swapBuffers(win);
    }

    RGFW_window_close(win);
    return 0;
}
```
What do you think, @ColleagueRiley ?

**Comment by ColleagueRiley** [comment]
@TheYahton This looks good, but I would like both types of event checking to be shown in the basic example. 

The use of actual drawing seems good as well as the comment clarifying that modern opengl can be used.

Also I just noticed that the `(u64)` cast is out of date and should be `(u16)` now. 

Finally, I'd prefer it be 

```c
while (RGFW_window_shouldClose(win) == RGFW_FALSE)
```

or 


```c
while (RGFW_window_shouldClose(win) == 0)
```

`!RGFW_window_shouldClose` is slightly less clear in my opinion.

**Comment by ColleagueRiley** [comment]
> > Although I would prefer the example list to be on the homepage
> 
> Then maybe leave the screenshot in README.md? examples
> 
> Or add a link to the web examples (https://colleagueriley.github.io/RGFW/)?

Yes, including both on the main page would be good.

**Comment by ColleagueRiley** [comment]
Ignore the web thing, it's just trying to deploy pages.

**Comment by TheYahton** [comment]
> @TheYahton This looks good, but I would like both types of event checking to be shown in the basic example.
like this?
```c
#define RGFW_IMPLEMENTATION
#include "RGFW.h"

void keyfunc(RGFW_window* win, u32 keycode, char keyName[16], u8 lockState, u8 pressed) {
    if (keycode == RGFW_Escape && pressed) {
        RGFW_window_setShouldClose(win);
    }
}

int main() {
    RGFW_window* win = RGFW_createWindow("a window", RGFW_RECT(0, 0, 800, 600), (u16)RGFW_CENTER);

    RGFW_setKeyCallback(keyfunc); // you can use callbacks like this if you want

    while (RGFW_window_shouldClose(win) == RGFW_FALSE) {
        while (RGFW_window_checkEvent(win)) {  // or RGFW_window_checkEvents(); if you only want callbacks
            // you can either check the current event yourself
            if (win->event.type == RGFW_mouseButtonPressed && win->event.button == RGFW_mouseLeft) {
                printf("You clicked at x: %d, y: %d\n", win->event.point.x, win->event.point.y);
            }

            // or use the existing functions
            if (RGFW_isMousePressed(win, RGFW_mouseRight)) {
                printf("The right mouse button was clicked at x: %d, y: %d\n", win->event.point.x, win->event.point.y);
            }
        }
        
        glClearColor(0.1f, 0.1f, 0.1f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        // You can use modern OpenGL techniques, but this method is more straightforward for drawing just one triangle.
        glBegin(GL_TRIANGLES);
        glColor3f(1, 0, 0); glVertex2f(-0.5, -0.5);
        glColor3f(0, 1, 0); glVertex2f(0.5, -0.5);
        glColor3f(0, 0, 1); glVertex2f(0, 0.5);
        glEnd();

        RGFW_window_swapBuffers(win);
    }

    RGFW_window_close(win);
    return 0;
}
```

**Comment by ColleagueRiley** [comment]
@TheYahton Sure, leaving it how it is would also be fine.

**Comment by TheYahton** [comment]
@ColleagueRiley , is everything fine?

**Comment by ColleagueRiley** [comment]
@TheYahton Yes, this all looks good

**Comment by ColleagueRiley** [comment]
@TheYahton Thanks for the pull request!

**Pull request merged**
