### PR TITLE
fix msvc compile error and add ogl33 demo

### PR DESCRIPTION
**Pull request by THISISAGOODNAME**

### CODE REVIEW

**Comment by ColleagueRiley** [comment]
Thank you, I'll look into it later before I pull it.

**Comment by ColleagueRiley** [comment]
Issues so far

1) you use CMake, why? CMake adds no value here

2) The sample code is written in C++, it should be written in C. This is a C library.

3) I don't really like your loader, it's a bit bloated and can be replaced with my opengl 3 loader. 

Other than those three things it looks pretty good.

**Comment by ColleagueRiley** [comment]
I'm just going to pull it and fix it myself

**Comment by ColleagueRiley** [comment]
The vulkan example still needs to be converted to C however

**Comment by THISISAGOODNAME** [comment]
I'm sorry, I didn't realize that RGFW is a C library.

**Comment by ColleagueRiley** [comment]
It's alright, would you mind rewriting the Vulcan example in C?

**Comment by THISISAGOODNAME** [comment]
I will try it during weekend.

**Pull request merged**
